// SPDX-FileCopyrightText: 2025 SternXD
// SPDX-License-Identifier: AGPL-3.0

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    'faq',
    {
      type: 'category',
      label: 'Xbox Setup',
      items: [
        'xbox-setup/xbox-developer-mode-setup',
      ],
    },
    {
      type: 'category',
      label: 'Emulation Guides',
      items: [
        'emulation/index',
        'emulation/chonkystation3-guide',
        'emulation/dolphin-guide',
        'emulation/panda3ds-guide',
        'emulation/ppsspp-guide',
        'emulation/retroarch-guide',
        'emulation/touchhle-guide',
        'emulation/xbsx2-guide',
        'emulation/flycast-guide',
      ],
    },
    {
      type: 'category',
      label: 'App Guides',
      items: [
        'apps/boxedwine-guide',
        'apps/gzdoom-guide',
        'apps/launchpass-guide',
        'apps/razeuwp-guide',
        'apps/sonic-adventure-blast2-uwp',
        'apps/sonic-unleashed-recompiled',
      ],
    },
    {
      type: 'category',
      label: 'Development Guides',
      items: [
        'development/index',
        'development/compiling-xbsx2-guide',
        'development/compiling-dolphin-guide',
        'development/compiling-xenia-guide',
        'development/compiling-mesa-guide',
      ],
    },
    {
      type: 'category',
      label: 'Helpful Links',
      items: [
        'helpful-links/index',
        'helpful-links/xbox-uwp-development',
        'helpful-links/visual-studio-2022-setup',
        'helpful-links/visual-studio-2026-setup',
        'helpful-links/worleydls-uwp-porting-notes',
      ],
    },
  ],
};

export default sidebars;
